"""init

Revision ID: 3e3d47ff479a
Revises: c079b028a308
Create Date: 2026-05-03 12:46:28.799965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3d47ff479a'
down_revision: Union[str, Sequence[str], None] = 'c079b028a308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispositivo_id'), 'dispositivo', ['id'], unique=False)
    op.create_table('leitura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('id_sensor', sa.Integer(), nullable=True),
    sa.Column('id_dispositivo', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leitura_id'), 'leitura', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leitura_id'), table_name='leitura')
    op.drop_table('leitura')
    op.drop_index(op.f('ix_dispositivo_id'), table_name='dispositivo')
    op.drop_table('dispositivo')
    # ### end Alembic commands ###
