import { Edit3, MapPin, Plus, RadioTower, Trash2, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useDeviceMutations, useDevices } from '../hooks/useWeatherData'
import type { ApiDispositivo, DispositivoInput } from '../types/api'
import { Badge, Button, Card, EmptyState, Skeleton } from '../components/ui'

const initialForm: DispositivoInput = { nome: '', latitude: -11.3289, longitude: -41.8644 }

export function StationsPage() {
  const devices = useDevices()
  const mutations = useDeviceMutations()
  const [editing, setEditing] = useState<ApiDispositivo | null>(null)
  const [form, setForm] = useState<DispositivoInput>(initialForm)
  const [showForm, setShowForm] = useState(false)

  function openForm(device?: ApiDispositivo) { setEditing(device || null); setForm(device ? { nome: device.nome, latitude: device.latitude, longitude: device.longitude } : initialForm); setShowForm(true) }
  async function submit(event: FormEvent) { event.preventDefault(); if (editing) await mutations.update.mutateAsync({ id: editing.id, data: form }); else await mutations.create.mutateAsync(form); setShowForm(false) }
  const pending = mutations.create.isPending || mutations.update.isPending

  return <><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Badge>CADASTRO</Badge><h1 className="mt-3 text-3xl font-bold tracking-tight">Estações próprias</h1><p className="mt-2 text-sm text-slate-500">Dispositivos cadastrados no backend existente.</p></div><Button onClick={() => openForm()} className="bg-brand-600 text-white hover:bg-brand-700"><Plus size={17} />Nova estação</Button></div>
  {devices.isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1, 2, 3].map((i) => <Card key={i} className="p-5"><Skeleton className="h-28" /></Card>)}</div> : devices.isError ? <EmptyState title="Não foi possível carregar as estações" description={devices.error.message} action={<Button onClick={() => devices.refetch()} className="bg-brand-600 text-white">Tentar novamente</Button>} /> : !devices.data?.length ? <EmptyState title="Nenhuma estação cadastrada" description="Cadastre uma estação própria para começar a acompanhar as leituras." action={<Button onClick={() => openForm()} className="bg-brand-600 text-white"><Plus size={16} />Cadastrar estação</Button>} /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{devices.data.map((device) => <Card key={device.id} className="p-5"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-brand-50 text-brand-600"><RadioTower size={21} /></div><Badge>PRÓPRIA</Badge></div><h2 className="mt-5 text-lg font-bold">{device.nome}</h2><p className="mt-1 text-xs text-slate-400">ID #{device.id}</p><div className="mt-4 flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-sm text-slate-500"><MapPin size={16} />{device.latitude.toFixed(5)}, {device.longitude.toFixed(5)}</div><div className="mt-4 flex gap-2"><Button onClick={() => openForm(device)} className="flex-1 border border-line bg-white text-slate-600"><Edit3 size={15} />Editar</Button><Button aria-label={`Excluir ${device.nome}`} onClick={() => { if (window.confirm(`Excluir a estação “${device.nome}”?`)) mutations.remove.mutate(device.id) }} className="border border-red-100 bg-red-50 px-3 text-red-600"><Trash2 size={15} /></Button></div></Card>)}</div>}
  {showForm && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/35 p-4" role="dialog" aria-modal="true" aria-labelledby="station-form-title"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 id="station-form-title" className="text-xl font-bold">{editing ? 'Editar estação' : 'Nova estação'}</h2><button type="button" aria-label="Fechar" onClick={() => setShowForm(false)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={20} /></button></div><div className="mt-6 space-y-4"><Input label="Nome" value={form.nome} onChange={(value) => setForm({ ...form, nome: value })} required /><Input label="Latitude" type="number" step="any" min="-90" max="90" value={form.latitude} onChange={(value) => setForm({ ...form, latitude: Number(value) })} required /><Input label="Longitude" type="number" step="any" min="-180" max="180" value={form.longitude} onChange={(value) => setForm({ ...form, longitude: Number(value) })} required /></div>{(mutations.create.isError || mutations.update.isError) && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{(mutations.create.error || mutations.update.error)?.message}</p>}<div className="mt-6 flex justify-end gap-2"><Button type="button" onClick={() => setShowForm(false)} className="bg-slate-100 text-slate-600">Cancelar</Button><Button type="submit" disabled={pending} className="bg-brand-600 text-white">{pending ? 'Salvando…' : 'Salvar estação'}</Button></div></form></div>}</>
}

function Input({ label, value, onChange, ...props }: { label: string; value: string | number; onChange: (value: string) => void } & Omit<React.InputHTMLAttributes<HTMLInputElement>, 'value' | 'onChange'>) { return <label className="block text-sm font-semibold text-slate-600">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-line px-3 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100" {...props} /></label> }
